// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rogjosgrwrlblpslmocr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZ2pvc2dyd3JsYmxwc2xtb2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0OTAzMzEsImV4cCI6MjA5MTA2NjMzMX0.Bym8ero9lGUIFbswljLyy3y-GjGPx-UcTzxH0V5lfr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});